### ISSUE TITLE
Route with keepAlive: true does not fire its focus hook when coming back to the kept alive instance

### ISSUE THREAD

**Issue by ChrisArasin** [lightning-js/blits#221]
I'm finding that if I have `keepAlive: true` on a route, navigate away from it, then navigate back, the `focus` hook does not fire on the page component. This means the proper child component on the page does not get refocused.

**Comment by michielvandergeest** [comment]
hey @ChrisArasin, the Portal page in the Blits example page has keep alive on it and it seems to work properly wiht passing the focus back to the previously focused item. It fires the focus hook on the item that was focused before navigating, but it indeed does not fire a focus event on the parent (or grand grand parents) of the item component.

Can you provide some details / examples how a focus event on the parent page (or other parent components) would be necessary ?

**Comment by michielvandergeest** [comment]
Hey @ChrisArasin, you are right about the `$hasFocus` property not being set when navigating back via the router. We' should have fixed that part in this commit: https://github.com/lightning-js/blits/pull/225, which should land in the next release

Does this also fix your initial issue?

**Comment by ChrisArasin** [comment]
Awesome! Yes, that should fix the visual bug I was encountering.

**Comment by michielvandergeest** [comment]
Cool! Good to hear :)

So you think we can close this issue? Or shall we keep it around, to see if we need to further address the hooks firing?

I still don't really think that it should fire the whole chain again, as the page is kept alive. So the only thing it should then do is ensure that the previously focused component, receives back it's focus, right?

But happy to hear if we've missed a use case or angle.

**Comment by ChrisArasin** [comment]
Yeah, I could go either way, but https://github.com/lightning-js/blits/issues/163 seems to cover that for now.
